# Docker Compose configuration for local development with vector database
version: '3.8'

services:
  # Main application
  chatbot-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - VECTOR_STORE_PATH=/app/data/vector_store
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/chatbot
    volumes:
      - ./data:/app/data
      - ./app:/app/app
    depends_on:
      - postgres
      - chroma
    restart: unless-stopped

  # PostgreSQL database for conversation storage
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: chatbot
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    restart: unless-stopped

  # Chroma vector database
  chroma:
    image: chromadb/chroma:latest
    ports:
      - '8001:8000'
    volumes:
      - chroma_data:/chroma/chroma
    environment:
      - CHROMA_SERVER_HOST=0.0.0.0
      - CHROMA_SERVER_HTTP_PORT=8000
    restart: unless-stopped

  # Optional: Jupyter notebook for experiments
  jupyter:
    build:
      context: .
      dockerfile: Dockerfile.jupyter
    ports:
      - '8888:8888'
    volumes:
      - ./notebooks:/app/notebooks
      - ./data:/app/data
      - ./app:/app/app
    environment:
      - JUPYTER_ENABLE_LAB=yes
    command: start-notebook.sh --NotebookApp.token='' --NotebookApp.password=''
    restart: unless-stopped

volumes:
  postgres_data:
  chroma_data:
